import type { MapImageData,MapMetadata,MapZone,NavigationObject,NavigationPath,RobotConfig,ValidationIssue } from '../models';
import { factoryObstacleRects } from '../map-engine/factorySeed';import { base64ToUint8 } from '../utils/files';import { pointInPixelRect,polygonsOverlap,segmentIntersectsPixelRect,segmentIntersectsPolygon } from '../geometry/collision';import { selfIntersects } from '../geometry/polygon';import { worldToPixel } from '../map-engine/coordinates';
export interface ValidationInput{metadata:MapMetadata;image?:MapImageData|null;objects:NavigationObject[];paths:NavigationPath[];zones:MapZone[];robot:RobotConfig}
const issue=(id:string,severity:ValidationIssue['severity'],type:string,message:string,objectId?:string,position?:{x:number;y:number},suggestedFix?:string):ValidationIssue=>({id,severity,type,message,objectId,position,suggestedFix});
const inBounds=(p:{x:number;y:number},m:MapMetadata)=>p.x>=m.originX&&p.y>=m.originY&&p.x<=m.originX+m.width*m.resolution&&p.y<=m.originY+m.height*m.resolution;
function occupancyReader(s:ValidationInput){if(!s.image?.occupancyBase64)return null;let data:Uint8Array;try{data=base64ToUint8(s.image.occupancyBase64)}catch{return null}if(data.length!==s.metadata.width*s.metadata.height)return null;return(p:{x:number;y:number})=>{const q=worldToPixel(p.x,p.y,s.metadata),x=Math.floor(q.x),y=Math.floor(q.y);if(x<0||y<0||x>=s.metadata.width||y>=s.metadata.height)return false;return data[y*s.metadata.width+x]===1}}
function segmentOccupied(a:{x:number;y:number},b:{x:number;y:number},occupied:(p:{x:number;y:number})=>boolean,resolution:number){const d=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(1,Math.ceil(d/Math.max(resolution,.01)));for(let i=0;i<=steps;i++){const t=i/steps;if(occupied({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}))return true}return false}
export function validateProject(s:ValidationInput):ValidationIssue[]{const out:ValidationIssue[]=[];const occupied=occupancyReader(s);const allIds=[...s.objects.map(x=>x.id),...s.paths.map(x=>x.id),...s.zones.map(x=>x.id)],counts=new Map<string,number>();for(const id of allIds)counts.set(id,(counts.get(id)??0)+1);
 for(const o of s.objects){if((counts.get(o.id)??0)>1)out.push(issue(`dup-${o.id}`,'error','duplicate_id',`Duplicate entity ID ${o.id}.`,o.id,{x:o.x,y:o.y},'Assign a unique ID.'));if(!inBounds(o,s.metadata))out.push(issue(`out-${o.id}`,'error','outside_map',`${o.name} is outside map boundaries.`,o.id,{x:o.x,y:o.y},'Move the object inside the map.'));const blocked=occupied?occupied(o):factoryObstacleRects.some(r=>pointInPixelRect(o,r,s.metadata));if(blocked)out.push(issue(`obs-${o.id}`,'error','object_in_obstacle',`${o.name} intersects an occupancy obstacle.`,o.id,{x:o.x,y:o.y},'Move the object into free space.'))}
 const noGo=s.zones.filter(z=>z.enabled&&z.type==='no_go');for(const path of s.paths){if((counts.get(path.id)??0)>1)out.push(issue(`dup-${path.id}`,'error','duplicate_id',`Duplicate entity ID ${path.id}.`,path.id,path.points[0]));if(path.points.length<2){out.push(issue(`short-${path.id}`,'error','invalid_path',`${path.name} requires at least two points.`,path.id,path.points[0]));continue}for(let i=0;i<path.points.length-1;i++){const a=path.points[i],b=path.points[i+1];if(Math.hypot(b.x-a.x,b.y-a.y)<1e-6){out.push(issue(`zero-${path.id}-${i}`,'error','zero_length_segment',`${path.name} contains a zero-length segment.`,path.id,a,'Move or remove the duplicate vertex.'));continue}const blocked=occupied?segmentOccupied(a,b,occupied,s.metadata.resolution):factoryObstacleRects.some(r=>segmentIntersectsPixelRect(a,b,r,s.metadata));if(blocked){out.push(issue(`pobs-${path.id}-${i}`,'error','path_obstacle',`${path.name} intersects an obstacle.`,path.id,a,'Reroute the segment through free space.'));break}const z=noGo.find(z=>segmentIntersectsPolygon(a,b,z.polygon));if(z){out.push(issue(`png-${path.id}-${i}`,'error','path_no_go',`${path.name} enters ${z.name}.`,path.id,a,'Reroute outside the No-Go Zone.'));break}}
 const required=s.robot.width+s.robot.safetyMargin*2;if((path.width??1)<required)out.push(issue(`clear-${path.id}`,'warning','clearance',`${path.name} width ${(path.width??1).toFixed(2)} m is below required ${required.toFixed(2)} m.`,path.id,path.points[Math.floor(path.points.length/2)],'Increase path width or reduce robot footprint/safety margin.'));const start=path.points[0],end=path.points.at(-1)!;const near=(pt:{x:number;y:number})=>s.objects.some(o=>Math.hypot(o.x-pt.x,o.y-pt.y)<.45)||s.paths.some(other=>other.id!==path.id&&other.points.some(q=>Math.hypot(q.x-pt.x,q.y-pt.y)<.45));if(!near(start)||!near(end))out.push(issue(`disc-${path.id}`,'warning','disconnected_path',`${path.name} has a disconnected endpoint.`,path.id,!near(start)?start:end,'Connect the endpoint to a waypoint or another path.'));if(path.type==='one_way'&&Math.hypot(end.x-start.x,end.y-start.y)<.1)out.push(issue(`dir-${path.id}`,'error','invalid_one_way',`${path.name} has no valid one-way direction.`,path.id,start))}
 for(const z of s.zones){if((counts.get(z.id)??0)>1)out.push(issue(`dup-${z.id}`,'error','duplicate_id',`Duplicate entity ID ${z.id}.`,z.id,z.polygon[0]));if(z.polygon.length<3||selfIntersects(z.polygon))out.push(issue(`poly-${z.id}`,'error','invalid_polygon',`${z.name} has an invalid/self-intersecting polygon.`,z.id,z.polygon[0],'Edit polygon vertices to remove intersections.'));if(z.polygon.some(p=>!inBounds(p,s.metadata)))out.push(issue(`zout-${z.id}`,'error','zone_outside_map',`${z.name} extends outside map boundaries.`,z.id,z.polygon.find(p=>!inBounds(p,s.metadata)),'Move all vertices inside the map.'))}
 for(let i=0;i<s.zones.length;i++)for(let j=i+1;j<s.zones.length;j++){const a=s.zones[i],b=s.zones[j];if(!a.enabled||!b.enabled||!polygonsOverlap(a.polygon,b.polygon))continue;const conflict=(a.type==='no_go'&&['slow','parking','loading','unloading'].includes(b.type))||(b.type==='no_go'&&['slow','parking','loading','unloading'].includes(a.type));if(conflict)out.push(issue(`conf-${a.id}-${b.id}`,'warning','zone_conflict',`${a.name} overlaps ${b.name}.`,a.id,a.polygon[0],'Review overlapping zone semantics.'))}return out}
