import { z } from 'zod';
const point=z.object({x:z.number().finite(),y:z.number().finite()});
const metadata=z.object({id:z.string(),name:z.string(),width:z.number().int().positive(),height:z.number().int().positive(),resolution:z.number().positive(),originX:z.number().finite(),originY:z.number().finite(),originYaw:z.number().finite()});
const image=z.object({dataUrl:z.string(),originalDataUrl:z.string().optional(),mimeType:z.string(),originalFilename:z.string(),sourceFormat:z.enum(['pgm','png','jpg','jpeg']),originalBase64:z.string().optional(),occupancyBase64:z.string().optional(),negate:z.union([z.literal(0),z.literal(1)]),occupiedThresh:z.number(),freeThresh:z.number()}).nullable();
const object=z.object({id:z.string(),name:z.string(),type:z.enum(['waypoint','home','charging_station','docking_station','pickup','dropoff','waiting','parking']),x:z.number(),y:z.number(),yaw:z.number(),description:z.string().optional(),enabled:z.boolean(),metadata:z.record(z.string(),z.unknown())});
const path=z.object({id:z.string(),name:z.string(),type:z.enum(['normal','preferred','one_way','bidirectional','restricted']),points:z.array(point).min(2),maxSpeed:z.number().optional(),width:z.number().optional(),safetyClearance:z.number().optional(),priority:z.number().optional(),robotTypes:z.array(z.string()).optional(),enabled:z.boolean()});
const zone=z.object({id:z.string(),name:z.string(),type:z.enum(['no_go','slow','restricted','parking','loading','unloading','human_traffic','safety']),polygon:z.array(point).min(3),maxSpeed:z.number().optional(),robotTypes:z.array(z.string()).optional(),enabled:z.boolean(),metadata:z.record(z.string(),z.unknown())});
const robot=z.object({name:z.string(),width:z.number().positive(),length:z.number().positive(),footprint:z.union([z.object({type:z.literal('rectangle'),width:z.number().positive(),length:z.number().positive()}),z.object({type:z.literal('circle'),radius:z.number().positive()}),z.object({type:z.literal('polygon'),points:z.array(point).min(3)})]),safetyMargin:z.number().nonnegative(),inflationRadius:z.number().nonnegative(),minimumClearance:z.number().nonnegative(),minimumTurningRadius:z.number().nonnegative(),maxSpeed:z.number().positive()});
export const AMRMapProjectFileSchema=z.object({format:z.literal('AMR_MAP_PROJECT'),version:z.literal('1.0'),project:z.object({id:z.string(),name:z.string(),metadata,image,objects:z.array(object),paths:z.array(path),zones:z.array(zone),robotConfigs:z.array(robot).min(1),createdAt:z.string(),updatedAt:z.string(),revision:z.number().int().nonnegative().default(1)})});
export function migrateProject(value:unknown){const v=value as {version?:unknown};if(v?.version==='1.0')return AMRMapProjectFileSchema.parse(value);throw new Error(`Project file version ${String(v?.version??'unknown')} is unsupported.`)}
