import { create } from 'zustand';
import type { AMRMapProjectFile,BuildingData,BuildingDoor,BuildingFloor,BuildingMeasurement,BuildingModel,BuildingWall,MapImageData,MapMetadata,MapZone,NavigationObject,NavigationPath,RobotConfig,ValidationIssue } from '../models';
import { defaultBuildingData } from '../models';
import { validateProject } from '../validation/validator';
import { saveProjectIndexedDb } from '../services/persistence/indexedDb';

const seedMetadata:MapMetadata={id:'factory-a-f1',name:'Factory A / Floor 1',width:850,height:620,resolution:.05,originX:-4,originY:-3,originYaw:0};
const obj=(id:string,name:string,type:NavigationObject['type'],x:number,y:number,yaw=0):NavigationObject=>({id,name,type,x,y,yaw,enabled:true,metadata:{}});
const seedObjects:NavigationObject[]=[obj('HOME-01','HOME-01','home',2,3),obj('CHARGE-01','CHARGE-01','charging_station',1,23),obj('CHARGE-02','CHARGE-02','charging_station',4,23),obj('PICKUP-A','PICKUP-A','pickup',28,24),obj('DROPOFF-A','DROPOFF-A','dropoff',34,7),obj('WAIT-01','WAIT-01','waiting',20,8),...Array.from({length:10},(_,i)=>obj(`WAYPOINT-${String(i+1).padStart(3,'0')}`,`WAYPOINT-${String(i+1).padStart(3,'0')}`,'waypoint',8+(i%5)*5,5+Math.floor(i/5)*14,(i%4)*Math.PI/2))];
const seedPaths:NavigationPath[]=[{id:'P-01',name:'Main Loop',type:'bidirectional',points:[{x:2,y:3},{x:8,y:5},{x:13,y:5},{x:18,y:5},{x:23,y:5},{x:28,y:5},{x:34,y:7}],maxSpeed:1.5,width:1.2,safetyClearance:.2,enabled:true},{id:'P-02',name:'Warehouse Spine',type:'one_way',points:[{x:8,y:5},{x:8,y:19},{x:13,y:19},{x:18,y:19},{x:23,y:19},{x:28,y:24}],maxSpeed:1,width:1,enabled:true}];
const seedZones:MapZone[]=[{id:'Z-NOGO',name:'No-Go: Paint Cell',type:'no_go',polygon:[{x:14,y:10},{x:19,y:10},{x:19,y:15},{x:14,y:15}],enabled:true,metadata:{}},{id:'Z-SLOW',name:'Slow: Loading',type:'slow',polygon:[{x:27,y:20},{x:38,y:20},{x:38,y:27},{x:27,y:27}],maxSpeed:.5,enabled:true,metadata:{}},{id:'Z-HUMAN',name:'Human Traffic',type:'human_traffic',polygon:[{x:3,y:11},{x:10,y:11},{x:10,y:16},{x:3,y:16}],enabled:true,metadata:{}}];
const seedRobot:RobotConfig={name:'TUG-600',width:.72,length:1.05,footprint:{type:'rectangle',width:.72,length:1.05},safetyMargin:.15,inflationRadius:.35,minimumClearance:.2,minimumTurningRadius:.65,maxSpeed:1.8};
const seedBuilding=defaultBuildingData(seedMetadata.name);

type Snapshot={metadata:MapMetadata;image:MapImageData|null;name:string;objects:NavigationObject[];paths:NavigationPath[];zones:MapZone[];robot:RobotConfig;building:BuildingData};
interface ProjectState{projectId:string;name:string;createdAt:string;revision:number;metadata:MapMetadata;image:MapImageData|null;objects:NavigationObject[];paths:NavigationPath[];zones:MapZone[];robot:RobotConfig;building:BuildingData;issues:ValidationIssue[];dirty:boolean;saveState:'saved'|'saving'|'unsaved'|'error';undo:Snapshot[];redo:Snapshot[];
 commit:()=>void;undoAction:()=>void;redoAction:()=>void;updateObject:(id:string,p:Partial<NavigationObject>)=>void;addObject:(o:NavigationObject)=>void;deleteIds:(ids:string[])=>void;addPath:(p:NavigationPath)=>void;updatePath:(id:string,p:Partial<NavigationPath>)=>void;replacePaths:(paths:NavigationPath[])=>void;addZone:(z:MapZone)=>void;updateZone:(id:string,p:Partial<MapZone>)=>void;updateRobot:(p:Partial<RobotConfig>)=>void;
 updateBuildingConfig:(p:Partial<BuildingData['config']>)=>void;addWall:(v:BuildingWall)=>void;updateWall:(id:string,p:Partial<BuildingWall>)=>void;addDoor:(v:BuildingDoor)=>void;updateDoor:(id:string,p:Partial<BuildingDoor>)=>void;addFloor:(v:BuildingFloor)=>void;updateFloor:(id:string,p:Partial<BuildingFloor>)=>void;addModel:(v:BuildingModel)=>void;updateModel:(id:string,p:Partial<BuildingModel>)=>void;addMeasurement:(v:BuildingMeasurement)=>void;updateMeasurement:(id:string,p:Partial<BuildingMeasurement>)=>void;
 validate:()=>ValidationIssue[];toProjectFile:()=>AMRMapProjectFile;saveLocal:()=>Promise<void>;loadProject:(f:AMRMapProjectFile)=>void;replaceMap:(metadata:MapMetadata,image:MapImageData,clearObjects:boolean)=>void;updateMapImage:(image:MapImageData)=>void;newProject:()=>void;markDirty:()=>void;}
const clone=<T,>(x:T):T=>structuredClone(x);
const snap=(s:ProjectState):Snapshot=>({metadata:clone(s.metadata),image:clone(s.image),name:s.name,objects:clone(s.objects),paths:clone(s.paths),zones:clone(s.zones),robot:clone(s.robot),building:clone(s.building)});
const initialId=crypto.randomUUID(),initialDate=new Date().toISOString();

export const useProjectStore=create<ProjectState>((set,get)=>({projectId:initialId,name:'Factory A / Floor 1',createdAt:initialDate,revision:1,metadata:seedMetadata,image:null,objects:seedObjects,paths:seedPaths,zones:seedZones,robot:seedRobot,building:seedBuilding,issues:[],dirty:true,saveState:'unsaved',undo:[],redo:[],
 commit:()=>set(s=>({undo:[...s.undo.slice(-79),snap(s)],redo:[]})),
 undoAction:()=>set(s=>{const prev=s.undo.at(-1);if(!prev)return{};return{...prev,undo:s.undo.slice(0,-1),redo:[snap(s),...s.redo],dirty:true,saveState:'unsaved'}}),
 redoAction:()=>set(s=>{const next=s.redo[0];if(!next)return{};return{...next,redo:s.redo.slice(1),undo:[...s.undo,snap(s)],dirty:true,saveState:'unsaved'}}),
 markDirty:()=>set({dirty:true,saveState:'unsaved'}),
 updateObject:(id,p)=>set(s=>({objects:s.objects.map(o=>o.id===id?{...o,...p}:o),dirty:true,saveState:'unsaved'})),
 addObject:o=>set(s=>({objects:[...s.objects,o],dirty:true,saveState:'unsaved'})),
 deleteIds:ids=>set(s=>({objects:s.objects.filter(o=>!ids.includes(o.id)),paths:s.paths.filter(p=>!ids.includes(p.id)),zones:s.zones.filter(z=>!ids.includes(z.id)),building:{...s.building,walls:s.building.walls.filter(x=>!ids.includes(x.id)),doors:s.building.doors.filter(x=>!ids.includes(x.id)),floors:s.building.floors.filter(x=>!ids.includes(x.id)),models:s.building.models.filter(x=>!ids.includes(x.id)),measurements:s.building.measurements.filter(x=>!ids.includes(x.id))},dirty:true,saveState:'unsaved'})),
 addPath:p=>set(s=>({paths:[...s.paths,p],dirty:true,saveState:'unsaved'})),updatePath:(id,p)=>set(s=>({paths:s.paths.map(x=>x.id===id?{...x,...p}:x),dirty:true,saveState:'unsaved'})),replacePaths:paths=>set({paths:clone(paths),dirty:true,saveState:'unsaved'}),
 addZone:z=>set(s=>({zones:[...s.zones,z],dirty:true,saveState:'unsaved'})),updateZone:(id,p)=>set(s=>({zones:s.zones.map(x=>x.id===id?{...x,...p}:x),dirty:true,saveState:'unsaved'})),updateRobot:p=>set(s=>({robot:{...s.robot,...p},dirty:true,saveState:'unsaved'})),
 updateBuildingConfig:p=>set(s=>({building:{...s.building,config:{...s.building.config,...p}},dirty:true,saveState:'unsaved'})),
 addWall:v=>set(s=>({building:{...s.building,walls:[...s.building.walls,v]},dirty:true,saveState:'unsaved'})),updateWall:(id,p)=>set(s=>({building:{...s.building,walls:s.building.walls.map(x=>x.id===id?{...x,...p}:x)},dirty:true,saveState:'unsaved'})),
 addDoor:v=>set(s=>({building:{...s.building,doors:[...s.building.doors,v]},dirty:true,saveState:'unsaved'})),updateDoor:(id,p)=>set(s=>({building:{...s.building,doors:s.building.doors.map(x=>x.id===id?{...x,...p}:x)},dirty:true,saveState:'unsaved'})),
 addFloor:v=>set(s=>({building:{...s.building,floors:[...s.building.floors,v]},dirty:true,saveState:'unsaved'})),updateFloor:(id,p)=>set(s=>({building:{...s.building,floors:s.building.floors.map(x=>x.id===id?{...x,...p}:x)},dirty:true,saveState:'unsaved'})),
 addModel:v=>set(s=>({building:{...s.building,models:[...s.building.models,v]},dirty:true,saveState:'unsaved'})),updateModel:(id,p)=>set(s=>({building:{...s.building,models:s.building.models.map(x=>x.id===id?{...x,...p}:x)},dirty:true,saveState:'unsaved'})),
 addMeasurement:v=>set(s=>({building:{...s.building,measurements:[...s.building.measurements,v]},dirty:true,saveState:'unsaved'})),updateMeasurement:(id,p)=>set(s=>({building:{...s.building,measurements:s.building.measurements.map(x=>x.id===id?{...x,...p}:x)},dirty:true,saveState:'unsaved'})),
 validate:()=>{const s=get(),issues=validateProject(s);set({issues});return issues},
 toProjectFile:()=>{const s=get();return{format:'AMR_MAP_PROJECT',version:'1.0',project:{id:s.projectId,name:s.name,metadata:clone(s.metadata),image:clone(s.image),objects:clone(s.objects),paths:clone(s.paths),zones:clone(s.zones),robotConfigs:[clone(s.robot)],building:clone(s.building),createdAt:s.createdAt,updatedAt:new Date().toISOString(),revision:s.revision}}},
 saveLocal:async()=>{set({saveState:'saving'});try{await saveProjectIndexedDb(get().toProjectFile());set({dirty:false,saveState:'saved'})}catch(e){set({saveState:'error'});throw e}},
 loadProject:f=>set({projectId:f.project.id,name:f.project.name,createdAt:f.project.createdAt,revision:f.project.revision,metadata:clone(f.project.metadata),image:clone(f.project.image),objects:clone(f.project.objects),paths:clone(f.project.paths),zones:clone(f.project.zones),robot:clone(f.project.robotConfigs[0]),building:clone(f.project.building??defaultBuildingData(f.project.name)),issues:[],dirty:false,saveState:'saved',undo:[],redo:[]}),
 replaceMap:(metadata,image,clear)=>set(s=>({metadata,image,name:metadata.name,objects:clear?[]:s.objects,paths:clear?[]:s.paths,zones:clear?[]:s.zones,building:clear?defaultBuildingData(metadata.name):{...s.building,config:{...s.building.config,buildingName:metadata.name}},issues:[],dirty:true,saveState:'unsaved',undo:[],redo:[]})),updateMapImage:image=>set({image,dirty:true,saveState:'unsaved'}),
 newProject:()=>{const id=crypto.randomUUID(),now=new Date().toISOString();set({projectId:id,name:'Untitled Map',createdAt:now,revision:1,metadata:{id,name:'Untitled Map',width:850,height:620,resolution:.05,originX:0,originY:0,originYaw:0},image:null,objects:[],paths:[],zones:[],robot:clone(seedRobot),building:defaultBuildingData('Untitled Map'),issues:[],dirty:false,saveState:'saved',undo:[],redo:[]})}
}));
