import { useEffect,useState } from 'react';import { importMapFiles,type ImportedMapPreview } from '../../services/import/mapImporter';import { getFileExtension } from '../../utils/files';import { useProjectStore } from '../../state/projectStore';import { useEditorStore } from '../../state/editorStore';
type Meta={resolution:number;originX:number;originY:number;originYaw:number};
export function ImportManager(){const p=useProjectStore(),resetEditor=useEditorStore(s=>s.resetEditor);const [files,setFiles]=useState<File[]>([]),[meta,setMeta]=useState<Meta>({resolution:.05,originX:0,originY:0,originYaw:0}),[needsMeta,setNeedsMeta]=useState(false),[preview,setPreview]=useState<ImportedMapPreview|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const handler=(ev:Event)=>{const next=(ev as CustomEvent<File[]>).detail??[];setError('');setPreview(null);setFiles(next);setNeedsMeta(!next.some(f=>['yaml','yml'].includes(getFileExtension(f.name))))};window.addEventListener('amr-import-files',handler);return()=>window.removeEventListener('amr-import-files',handler)},[]);
 const parse=async(useMeta:boolean)=>{setLoading(true);setError('');try{setPreview(await importMapFiles(files,useMeta?meta:undefined));setNeedsMeta(false)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 useEffect(()=>{if(files.length&&!needsMeta)void parse(false)},[files,needsMeta]);
 const close=()=>{setFiles([]);setPreview(null);setNeedsMeta(false);setError('')};const apply=(clear:boolean)=>{if(!preview)return;p.replaceMap(preview.metadata,preview.image,clear);resetEditor();close()};
 if(!files.length&&!error)return null;return <div className="modalback"><div className="modal"><h3>Import Map</h3>{loading?<div className="loading">Loading map…<br/><small>Parsing occupancy data…</small></div>:error?<><div className="errorbox">{error}</div><div className="modalactions"><button onClick={close}>Close</button></div></>:needsMeta?<><p>No YAML metadata was selected. Enter map coordinates before loading.</p><div className="formgrid"><Num label="Resolution (m/px)" value={meta.resolution} set={v=>setMeta({...meta,resolution:v})}/><Num label="Origin X" value={meta.originX} set={v=>setMeta({...meta,originX:v})}/><Num label="Origin Y" value={meta.originY} set={v=>setMeta({...meta,originY:v})}/><Num label="Origin Yaw (rad)" value={meta.originYaw} set={v=>setMeta({...meta,originYaw:v})}/></div><div className="modalactions"><button onClick={close}>Cancel</button><button className="primary" disabled={!Number.isFinite(meta.resolution)||meta.resolution<=0} onClick={()=>void parse(true)}>Load Preview</button></div></>:preview?<><div className="previewgrid"><span>File</span><b>{preview.yamlFile??'(image only)'}</b><span>Image</span><b>{preview.imageFile}</b><span>Size</span><b>{preview.metadata.width} × {preview.metadata.height} px</b><span>Resolution</span><b>{preview.metadata.resolution} m/px</b><span>World Size</span><b>{(preview.metadata.width*preview.metadata.resolution).toFixed(2)} × {(preview.metadata.height*preview.metadata.resolution).toFixed(2)} m</b><span>Origin</span><b>{preview.metadata.originX}, {preview.metadata.originY}, {preview.metadata.originYaw}</b></div>{(p.objects.length||p.paths.length||p.zones.length)?<div className="warnbox">This project contains {p.objects.length} objects, {p.paths.length} paths, and {p.zones.length} zones. Replacing the map may make their coordinates invalid.</div>:null}<div className="modalactions"><button onClick={close}>Cancel</button>{(p.objects.length||p.paths.length||p.zones.length)?<button onClick={()=>apply(false)}>Replace + Keep Objects</button>:null}<button className="primary" onClick={()=>apply(true)}>Import Map{p.objects.length||p.paths.length||p.zones.length?' + Clear Objects':''}</button></div></>:null}</div></div>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="field"><span>{label}</span><input type="number" step="0.01" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
